server:
  port: 8500
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8801/eureka, http://localhost:8802/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 配置路由，注意这里是个列表，每一项都包含了很多信息
      routes:
      - id: engine   # 路由名称
        uri: lb://engine  # 路由的地址，lb表示使用负载均衡到微服务，也可以使用http正常转发
        predicates: # 路由规则，断言什么请求会被路由
        - Path=/gateway/engine/**  # 只要是访问的这个路径，一律都被路由到上面指定的服务
        filters:
        - AddRequestHeader=Test, HelloWorld!
    nacos:
      discovery:
        # 配置中心服务器地址，也就是Nacos地址,这里用nginx做LB
        server-addr: 192.168.2.104:80