server:
  port: 9003
spring:
  application:
    name: index
  cloud:
    nacos:
      discovery:
        # 配置中心服务器地址，也就是Nacos地址,这里用nginx做LB
        server-addr: 192.168.2.104:80
    sentinel:
      transport:
        # 添加监控页面地址即可
        dashboard: localhost:8858
management:
  endpoints:
    web:
      exposure:
        include: '*'

